apiVersion: v1
kind: Service
metadata:
  labels:
    app: vof-mrm-redis
  name: redis-service
  namespace: default
spec:
  externalTrafficPolicy: Local
  ports:
    - name: server-port
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: vof-mrm-redis
  type: NodePort
