- name: Downloading and installing logging agent
  shell: 
    chdir: /home/vof
    cmd: |
      curl -sSO https://dl.google.com/cloudagents/install-logging-agent.sh
      bash /home/vof/installing-logging-agent.sh
      rm -f /home/vof/installing-logging-agent.sh
  become: yes
