apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    name: redis
  name: redis
spec:
  ports:
    - name: tcp
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis
  sessionAffinity: None
