apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: redis
  namespace: redis
  labels:
    app: redis
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
spec:
  tls:
    - secretName: {{ PROJECT_NAME }}-tls-secrets
  rules:
  - host: vof-redis.andela.com
    http:
      paths:
      - path: /
        backend:
          serviceName: vof
          servicePort: http
  - host: activo-redis.andela.com
    http:
      paths:
      - path: /activo
        backend:
          serviceName: activo
          servicePort: http
  - host: mrm-redis.andela.com
    http:
      paths:
      - path: /activo
        backend:
          serviceName: mrm
          servicePort: http
